# settings
float32_matmul_precision: high
random_seed: 114514

# dataloader
dataloader_workers: 12
dataloader_prefetch_factor: 2
oversampling_weights: [ 1, 1, 1 ] # full_label, weak_label, no_label
batch_max_length: 500 # unit: seconds
binning_length: 5000 # unit: seconds
drop_last: False

# network
backbone_net:
  network_name: unet
  n_dims: 128
  down_sampling_factor: 3
  down_sampling_times: 7
  channels_scaleup_factor: 1.5

optimizer_config:
  total_steps: 5000
  weight_decay: 0.1
  lr:
    backbone: 0.001
    head: 0.001
  freeze:
    backbone: False
    head: False

loss_config:
  losses:
    weights: [50.0, 1.0, 0.1]
  function:
    num_bins: 10
    alpha: 0.999
    label_smoothing: 0.08

# trainer
accelerator: auto
devices: auto # num_devices
precision: bf16-mixed # bf16-mixed , 32-true
gradient_clip_val: 1.0
gradient_clip_algorithm: norm #value
val_check_interval: 100